/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soul_ffmpegdemo_Player */

#ifndef _Included_com_soul_ffmpegdemo_Player
#define _Included_com_soul_ffmpegdemo_Player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soul_ffmpegdemo_Player
 * Method:    playVideo
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_soul_ffmpegdemo_Player_playVideo
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
